<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Tomas.EventSystemHelper.Kafka</PackageId>
    <RepositoryUrl>https://github.com/TomciusRomcius/ECommerceBackend.EventSystemHelper.Kafka</RepositoryUrl>
    <Version>1.0.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.10.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventSystemHelper\EventSystemHelper.csproj" />
  </ItemGroup>

</Project>